// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkcOyCotLBUL42JTx_O0i3JFnX7nwSw08',
    appId: '1:548427842369:web:2d6e01a2f381f670bb57c0',
    messagingSenderId: '548427842369',
    projectId: 'friend-zone-22e6b',
    authDomain: 'friend-zone-22e6b.firebaseapp.com',
    storageBucket: 'friend-zone-22e6b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD852NhAqH-P5NUaoKJW159bgYZai5jqXw',
    appId: '1:548427842369:android:1c00725c15797a6fbb57c0',
    messagingSenderId: '548427842369',
    projectId: 'friend-zone-22e6b',
    storageBucket: 'friend-zone-22e6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAejmG1yZYcH_O0YnIKrZhFrNDX94Umx9k',
    appId: '1:548427842369:ios:c51dda10c92a167abb57c0',
    messagingSenderId: '548427842369',
    projectId: 'friend-zone-22e6b',
    storageBucket: 'friend-zone-22e6b.appspot.com',
    iosClientId: '548427842369-epuj9n77cn3i5bclhsleo37ktpc8ncif.apps.googleusercontent.com',
    iosBundleId: 'com.example.agoraFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAejmG1yZYcH_O0YnIKrZhFrNDX94Umx9k',
    appId: '1:548427842369:ios:c51dda10c92a167abb57c0',
    messagingSenderId: '548427842369',
    projectId: 'friend-zone-22e6b',
    storageBucket: 'friend-zone-22e6b.appspot.com',
    iosClientId: '548427842369-epuj9n77cn3i5bclhsleo37ktpc8ncif.apps.googleusercontent.com',
    iosBundleId: 'com.example.agoraFlutter',
  );
}
